# Generated by Django 5.2.1 on 2025-05-12 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_author_book_delete_choice_delete_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_name',
            new_name='title',
        ),
    ]
