# Generated by Django 5.2.1 on 2025-05-12 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_book_name_book_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='book_name',
        ),
    ]
